import Head from 'next/head'
import AboutUs from '../components/About-us'
import Footer from '../components/Footer'
import HeroSection from '../components/HeroSection'
import NavHeader from '../components/NavHeader'
import Updates from '../components/Updates'
import VideoClips from '../components/VideoClips'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavHeader />
      <HeroSection />
      <AboutUs />
      <Updates />
      <VideoClips />
      <Footer />
    </div>
  )
}
